version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: ⬆️ 
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "/"
    commit-message:
      prefix: ⬆️ 
    schedule:
      interval: "monthly"
