[workspace]
resolver = "3"
default-members = ["client"]

members = ["client", "services/index-git-repositories", "settings"]

[workspace.package]
edition = "2024"
version = "1.1.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
