[package]
name = "centerpiece"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
async-trait = "0.1.73"
chrono = "0.4.26"
iced = { version = "0.10.0", features = ["svg"] }
